<BottomNavWidget>:
    MDBottomNavigation:
        MDBottomNavigationItem:
            name: 'screen 1'
            icon: "home"

        MDBottomNavigationItem:
            name: 'screen 2'
            icon: "equalizer"
        
        MDBottomNavigationItem:
            name: 'screen 3'
            icon: "account-multiple"

        MDBottomNavigationItem:
            name: 'screen 4'
            icon: "account-multiple"