#File name: swipeable_image_widget.kv



<SwipeableImageWidget>:
    do_scroll_x: True
    do_scroll_y: False
    bar_width: 0
    md_bg_color: (1,1)
    source: ""
    ScrollView:
        size_hint: (1,1)
        scroll_x: self.scroll_x
        scroll_y: self.scroll_y
        FitImage:
            id: image
            source: root.source
            size_hint_x: None
            width: app.size[0]
            size_hint_y: 1