#Dynamically generated, listing: 16 imports
from screens.statistics.weekly_activity_screen.weekly_activity_screen import WeeklyActivityScreen
from screens.statistics.monthly_activity_screen.monthly_activity_screen import MonthlyActivityScreen
from screens.statistics.daily_activity_screen.daily_activity_screen import DailyActivityScreen
from screens.activity.activity_screen.activity_screen import ActivityScreen
from screens.activity.home_screen.home_screen import HomeScreen
from screens.other.settings_screen.settings_screen import SettingsScreen
from screens.other.profile_edit_screen.profile_edit_screen import ProfileEditScreen
from screens.other.profile_screen.profile_screen import ProfileScreen
from screens.authentication.log_in_screen.log_in_screen import LogInScreen
from screens.authentication.sign_up_screen.sign_up_screen import SignUpScreen
from custom_widgets.input_widget.input_widget import InputWidget
from custom_widgets.bottom_nav_widget.bottom_nav_widget import BottomNavWidget
from custom_widgets.oval_blue_button_widget.oval_blue_button_widget import OvalBlueButtonWidget
from custom_widgets.button_widget.button_widget import ButtonWidget
from custom_widgets.template_widget.template_widget import TemplateWidget
from custom_widgets.authentication.top_menu_widget.top_menu_widget import TopMenuWidget
#End of imports
