#File name: profile_edit_screen.kv


<ProfileEditScreen>:
    name: "pes"
    id: pes
    TopReturnButtonWidget:
        release_func: root.return_to_profile
    MDLabel:
        pos_hint: {"center_x":0.5,"center_y":0.9}
        text: "Edit Profile"
        font_size: "28dp"
        font_name: app.fonts["sans_bold"]
        halign: "center"
    MDBoxLayout:
        MDLabel:
            text: "Profile edit screen"