#File name: title_separator_widget.kv

<TitleSeparatorWidget>:
    size_hint: (0.92,0.1)
    title_text: "Enter text"
    MDLabel:
        pos_hint: {"center_x":0.85,"center_y":0.7}
        id: label
        text: root.title_text
        color: [1, 1, 1, 0.65]

    MDLabel:
        pos_hint: {"center_x":0.5,"center_y":0.5}
        id: label
        text: "__________________________________________________"
        color: [1, 1, 1, 0.6]