# File name: main_frame.kv
#:import FadeTransition kivy.uix.screenmanager.FadeTransition

<MainScreenManager>:
    transition: FadeTransition()
    id: manager
    name: "manager"
    SettingsScreen:
    SignUpScreen:
    SecondSignUpScreen:
    LogInScreen:
    ForgotPasswordScreen:
    HomeScreen:
    ActivityScreen:
    DailyActivityScreen:
    WeeklyActivityScreen:
    MonthlyActivityScreen:
    ProfileScreen:
    ProfileEditScreen: