#File name: profile_screen.kv


<ProfileScreen>:
    name: "pfs"
    id: pfs
    MDBoxLayout:
        MDLabel:
            text: "Profile Screen"
        Button:
            text:"sign out"
            color: app.primary_colors["error_color"]
            background_color: (0,0,0,0)
            pos_hint: {"center_x":0.5,"center_y":0.2}
            on_release:
                root.sign_out(self)
    BottomNavWidget:
        selected: 4